facebook-react-guide-with-rails/config/routes.rb
Rails.application.routes.draw do
  root "sections#index"

  resources :sections, only: [:index, :show]
end

facebook-react-guide-with-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

facebook-react-guide-with-rails/app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  require 'coderay'
  before_filter :set_sections # Don't actually do this! This is just simulating API/Database calls

  def index
  end

  def show
    @section = @sections.select { |section| section[:num] == params[:id] }
    @section = @section[0] unless @section.empty?
  end

  private
  def set_sections
    @sections = [
      {
        num: "1",
        name: "Displaying Data",
        origin_url: "https://facebook.github.io/react/docs/displaying-data.html",
        component_name: "HelloWorld",
        template_name: "hello_world.js.jsx",
        props: {date: Time.now.strftime('%H:%M:%S GMT%z (%Z)')},
        description: "Simple example of how React displays data and keeps the interface up-to-date."
      },

      {
        num: "1-1",
        name: "JSX in Depth",
        origin_url: "https://facebook.github.io/react/docs/jsx-in-depth.html",
        component_name: "JSXInDepth",
        template_name: "jsx_in_depth.js.jsx",
        description: "JSX is a Javascript syntax extension that looks similar to XML."
      },

      {
        num: "2",
        name: "Interactivity and Dynamic UIs",
        origin_url: "https://facebook.github.io/react/docs/interactivity-and-dynamic-uis.html",
        component_name: "likeButton",
        template_name: "interactivity_and_dynamic_uis.js.jsx",
        description: "Demonstration of how to make UIs interactive."
      },
      {
        num: "3",
        name: "Multiple Components",
        origin_url: "https://facebook.github.io/react/docs/multiple-components.html",
        template_name: "multiple_components.js.jsx",
        component_name: "Avatar",
        props: {username: 'react'},
        description: "React encourages the use of building components that reuse other components with well-defined interfaces."
      },
      {
        num: "4",
        name: "Reusable Components",
        origin_url: "https://facebook.github.io/react/docs/reusable-components.html",
        template_name: "reusable_components.js.jsx",
        component_name: "ReusableComponents",
        props: {},
        description: "React provides several different features to promote reusability."
      }
    ]
  end
end

facebook-react-guide-with-rails/app/helpers/application_helper.rb
module ApplicationHelper
  def coderay(syntax, text)
    wrapped_text = "#{"<pre lang=\"#{syntax}\"><code lang=\"#{syntax}\">"}#{text}#{"</code></pre>"}"
    wrapped_text.gsub(/\<pre( lang="(.+?)")?\>\<code( lang="(.+?)")?\>(.+?)\<\/code\>\<\/pre\>/m) do
      lang = $4
      format_text = CGI.unescapeHTML($5).gsub /\<code( lang="(.+?)")?\>|\<\/code\>/, ""
      CodeRay.scan(format_text, lang).div(:css => :class)
    end
  end
end

facebook-react-guide-with-rails/app/helpers/sections_helper.rb
module SectionsHelper
end

facebook-react-guide-with-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FacebookReactWithRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

facebook-react-guide-with-rails/app/views/sections/index.html.erb
<div id="section-index" class="row">
  <div class="md-col-12">
    <h2 class="index-heading text-center">Guide Index</h2>
  </div>
  <div class="md-col-12">
    <table class="table table-striped table-bordered">
      <tr>
        <th>Section Number</th>
        <th>Rails Example</th>
        <th>Description</th>
        <th>Source</th>
      </tr>
      <% @sections.each do |section| %>
        <tr>
          <td><%= section[:num] %></td>
          <td><%= link_to section[:name], section_path(id: section[:num]) %></td>
          <td><%= section[:description] %></td>
          <td><a href="<%= section[:origin_url] %>">URL</a></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

facebook-react-guide-with-rails/app/views/sections/show.html.erb
<h1 class="page-header"> <%= link_to '←', :back %> <%= @section[:name] %></h1>

<div class="panel panel-info">
  <div class="panel-heading">
    <%= @section[:description] %>
  </div>
  <div class="panel-body">
    <div class="panel panel-default">
      <div class="panel-heading">
        Demo
      </div>
      <div class="panel-body">
        <%= react_component @section[:component_name], @section[:props], {id: 'example'} %>
      </div>
    </div>
    <hr>
    <%= raw coderay('javascript', (render file: "/app/assets/javascripts/components/#{@section[:template_name]}", layout: false)) %>
  </div>
</div>